Misc cleanup for treeline
softprops/treeline pull request #5
Opened 2021-08-24 17:46 UTC by epage

Separating these out from my work for #4 but wanting to make sure I am building on a solid base.

2021-08-27 16:53 UTC, epage commented
@softprops since it looks like [my crates are the only public clients](https://crates.io/crates/treeline/reverse_dependencies), would you like me to take over maintenance?

2021-08-29 01:36 UTC, softprops requested changes

2021-08-29 01:36 UTC, softprops commented on .github/workflows/ci.yml
> +      uses: actions-rs/toolchain@v1
Could we use https://github.com/hecrj/setup-rust-action instead? I tend to prefer this as it's more inline with other gh setup-xxxlang-actions.

2021-08-29 01:46 UTC, softprops commented on .github/workflows/ci.yml
> +    - uses: Swatinem/rust-cache@v1
Just being mindful of bringing in new dependencies. I like the thoughtfulness here but what’s the impact of this on a project that doesn’t have any dependencies? 

If change provides a significant build impact i generally prefer using the official gh actions cache action with cargos official recommendation https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci

2021-08-29 01:49 UTC, softprops commented on .github/workflows/ci.yml
> +    - '!/docs/**'
I think this my have been a copy past error. This folder does not exist

2021-08-29 01:50 UTC, softprops commented on .github/workflows/ci.yml
> +    - "!/LICENSE-*"
This pattern does not match the LICENSE file in this repo

2021-08-29 01:51 UTC, softprops commented on .github/workflows/ci.yml
> +    - '!/docs/**'
Same as above. These are likely copy paste errors

2021-08-29 01:53 UTC, softprops requested changes
The code changes look good. I think there is some clean up useful for ci. Thoughts on splitting the code changes from the move to gh actions into two separate pulls to move this forward?

if you’d like I could grab the actions bits. I have a standard actions recipe intend to use which works well for me

2021-08-29 02:37 UTC, epage commented
> if you’d like I could grab the actions bits. I have a standard actions recipe intend to use which works well for me

Feel free.  I was just applying a subset of my standard template (which is why some things were superfluous, consistency for me was easier for maintaining than customizing exactly to each situation).

2021-08-29 02:39 UTC, epage commented on .github/workflows/ci.yml
> +    - "!/LICENSE-*"
Hadn't noticed this is just MIT.  I have no license preference so I just default to the [API guidelines](https://rust-lang.github.io/api-guidelines/necessities.html#c-permissive).  Any thoughts on switching to the combo license?

2021-08-29 05:31 UTC, softprops commented on .github/workflows/ci.yml
> +    - "!/LICENSE-*"
I’ll look into it but that feels a bit out of scope for the changes was thinking you were looking to add

2021-08-30 14:21 UTC, epage commented
The GH actions have been removed from this PR.

2021-09-06 02:12 UTC, softprops approved these changes

2021-09-06 02:12 UTC, merged